dogcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # In this case '' represents the root route
    path('', include('main_app.urls'))
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/',views.about, name='about'),
    # route for dogs index
    path('dogs/', views.dogs_index, name='index'),
    #route for the detail page
    path('dogs/<int:dog_id>/', views.dogs_detail, name='detail'),
    # new route used to show a form and create a dog
    path('dogs/create/', views.DogCreate.as_view(), name='dogs_create'),
    # pk is what the django views is expecting as a param if we need one, which is short for primary key
    # aka the dog_id
    path('dogs/<int:pk>/update/', views.DogUpdate.as_view(), name='dogs_update'),
    path('dogs/<int:pk>/delete/', views.DogDelete.as_view(), name='dogs_delete'),
    path('dogs/<int:dog_id>/add_walking/', views.add_walking, name='add_walking'),
    # associate a treat with a dog (M:M)
    path('dogs/<int:dog_id>/assoc_treat/<int:treat_id>/', views.assoc_treat, name='assoc_treat'),
    # remove a treat for a dog
    path('dogs/<int:dog_id>/remove_treat/<int:treat_id>/', views.remove_treat, name='remove_treat'),
    path('treats/', views.TreatList.as_view(), name='treats_index'),
    path('treats/<int:pk>/', views.TreatDetail.as_view(), name='treats_detail'),
    path('treats/create/', views.TreatCreate.as_view(), name='treats_create'),
    path('treats/<int:pk>/update/', views.TreatUpdate.as_view(), name='treats_update'),
    path('treats/<int:pk>/delete/', views.TreatDelete.as_view(), name='treats_delete'),
]

main_app/models.py
from django.db import models
# Import the reverse function
from django.urls import reverse

# Create your models here.

class Treat(models.Model):
    name = models.CharField(max_length=50)
    brand = models.CharField(max_length=20)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('treats_detail', kwargs={'pk': self.id})

class Dog(models.Model):
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField()
    # Add the M:M relationship
    treats = models.ManyToManyField(Treat)
    
    #this function will get called on a create or update on a Class Based View in order redirect the user
    def get_absolute_url(self):
        # detail is referring to the name of the route
        # path('dogs/<int:dog_id>/', views.dogs_detail, name="detail"),
        return reverse('detail', kwargs={'dog_id': self.id})

# Set up Field Choices
SCHEDULE = (
    ('M', 'Morning'),
    ('A', 'Afternoon'),
    ('N', 'Night'),
)

class Walking(models.Model):
    # the first optional positional argument overrides the label
    date = models.DateField('walking date')
    schedule = models.CharField(
        'walking schedule',
        max_length=1, 
        choices=SCHEDULE,  
        default=SCHEDULE[0][0]  # 'M'
    )

    # create the dog_id FK (Foriegn Key)
    # on_Delete is saying if we delete a dog, delete all of the walkings the dog has, so no walkings exist without a dog
    dog = models.ForeignKey(Dog, on_delete=models.CASCADE)

    def __str__(self):
        # obtaining the human readable value of a Field.choice ('Morning')
        return f"{self.get_schedule_display()} on {self.date}"
    
    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Walking

class WalkingForm(ModelForm):
    class Meta:
        model = Walking
        fields = ['date', 'schedule']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Dog, Treat
from .forms import WalkingForm


# Define the home view
def home(request):
    return render(request, 'home.html')

# Define the about view
def about(request):
    return render(request, 'about.html')

# Define the index view
def dogs_index(request):
    dogs = Dog.objects.all()
    return render(request, 'dogs/index.html', {'dogs': dogs})

# Define the detail view
def dogs_detail(request, dog_id):
    dog = Dog.objects.get(id = dog_id)
    # we want to find the treats that don't belong to the dog!
    # id__in syntax is what call field lookups, get, exclude, or filter
    treats_dog_doesnt_have = Treat.objects.exclude(
        id__in=dog.treats.all().values_list('id'))

    # instantiate WalkingForm to be rendered in the template
    walking_form = WalkingForm()
    return render(request, 'dogs/detail.html', {'dog': dog, 'walking_form': walking_form,'treats': treats_dog_doesnt_have})

def assoc_treat(request, dog_id, treat_id):
    dog = Dog.objects.get(id=dog_id)
    dog.treats.add(treat_id)
    # option 2
    # Dog.objects.get(id=dog_id).treats.add(treat_id)
    return redirect('detail', dog_id=dog_id)

def remove_treat(request, dog_id, treat_id):
    dog = Dog.objects.get(id=dog_id)
    dog.treats.remove(treat_id)
    # option 2
    # Dog.objects.get(id=dog_id).treats.remove(treat_id)
    return redirect('detail', dog_id=dog_id)

class DogCreate(CreateView):
    model = Dog
    fields = '__all__'

class DogUpdate(UpdateView):
    model = Dog 
    # exclude the name from update  
    fields = ['breed', 'description', 'age'] 

class DogDelete(DeleteView):
    model = Dog
    success_url = '/dogs/' # if we delete a dog, we'll need to redirect to the dogs index page since that dog doesn't exist anymore.,

def add_walking(request, dog_id):
    # we need to create a modelForm instance using the data from request.POST
    form = WalkingForm(request.POST)
    # validate the form, so make sure the inputs are of the correct type and shape
    if form.is_valid():
        # were creating an object to save to the database, but don't save yet, because
        # we need to add dog_id
        new_walking = form.save(commit=False)
        new_walking.dog_id = dog_id
        new_walking.save()  # saves the walking to the database!
    # import redirect at the top
    return redirect('detail', dog_id=dog_id) #can be shorten as redirect('detail', dog_id)

class TreatList(ListView):
    model = Treat


class TreatDetail(DetailView):
    model = Treat


class TreatCreate(CreateView):
    model = Treat
    fields = '__all__'


class TreatUpdate(UpdateView):
    model = Treat
    fields = ['name', 'brand']


class TreatDelete(DeleteView):
    model = Treat
    success_url = '/treats/'

main_app/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dog Collector</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block content %}
    <h1>About the Dog Collector</h1>
    <hr />
    {% endblock %}
    <p>Hire the Dog Collector!</p>
    <footer>All Rights Reserved, &copy; 2022 Dog Collector</footer>
</body>
</html>

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Dog Collector</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    </head>
    <body>
    <header class="navbar-fixed">
        <nav>
        <div class="nav-wrapper">
            <ul>
                <li><a href="/" class="left brand-logo">&nbsp;&nbsp;DogCollector</a></li>
            </ul>
            <ul class="right">
                <li><a href="{% url 'about' %}">About</a></li>
                <li><a href="{% url 'treats_create' %}">Add a Treat</a></li>
                <li><a href="{% url 'treats_index' %}">View All Treats</a></li>
                <li><a href="{% url 'index' %}">View All My Dogs</a></li>
                <li><a href="{% url 'dogs_create' %}">Add a Dog</a></li>
            </ul>
        </div>
        </nav>
    </header>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
    <footer class="page-footer">
        <div class="right">All Rights Reserved, &copy; 2022 Cat Collector &nbsp;</div>
    </footer>
    </body>
</html>

main_app/templates/dogs/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Dog Details</h1>

<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content">
            <span class="card-title">{{ dog.name }}</span>
            <p>Breed: {{ dog.breed }}</p>
            <p>Description: {{ dog.description }}</p>
            {% if dog.age > 0 %}
                <p>Age: {{ dog.age }}</p>
            {% else %}
                <p>Age: Kitten</p>
            {% endif %}
            </div>
            <div class="card-action">
                <a href="{% url 'dogs_update' dog.id %}">Edit</a>
                <a href="{% url 'dogs_delete' dog.id %}">Delete</a>
            </div>
        </div>
    </div>

    <div class="col s6">
    <form action="{% url 'add_walking' dog.id %}" method="post">
        {% csrf_token %}
        {{ walking_form.as_p }}
        <input type="submit" class="btn" value="Add Walking">
    </form>
    <table class="striped">
        <thead>
            <tr><th>Walking Date</th><th>Walking Schedule</th></tr>
        </thead>
        <tbody>
            {% for walking in dog.walking_set.all %}
            <tr>
                <td>{{walking.date}}</td>
                <td>{{walking.get_schedule_display}}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>
</div>
<hr>
<div class="row">
    <div class="col s6">
    <h3>{{ dog.name }}'s Treats</h3>
    {% if dog.treats.count %}
        {% for treat in dog.treats.all %}
        <div class="card">
            <div class="card-content">
              <span class="card-title">
                A <span style="color: teal">{{ treat.brand }}</span> {{ treat.name }}
            </span>
            <div class="card-action">
				<form action="{% url 'remove_treat' dog.id treat.id %}" method="post">
					{% csrf_token %}
					<button type="submit" class="btn">Remove</button>
				</form>
			  </div>
            </div>
        </div>
        {% endfor %}
    {% else %}
        <h5>No treats :(</h5>
    {% endif %}
    </div>

	<!-- Available treats will come after this line -->
	<div class="col s6">
		<h3>Available Treats</h3>
		{% if treats.count %}
		{% for treat in treats.all %}
		  <div class="card">
			<div class="card-content">
				<span class="card-title">
					A <span style="color: teal">{{treat.brand}}</span> {{treat.name}}
				</span>
			</div>
			<div class="card-action">
				<form action="{% url 'assoc_treat' dog.id treat.id %}" method="post">
					{% csrf_token %}
					<button type="submit" class="btn">Add</button>
				</form>
			</div>
		  </div>
		{% endfor %}
		{% else %}
		<h5>{{dog.name}} Already Has All Treats Available</h5>
		{% endif %}
	</div>
</div>

<script>
    const dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    });
    const selectEl = document.getElementById('id_schedule');
	M.FormSelect.init(selectEl)
</script>
{% endblock %}

main_app/templates/dogs/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Dog List</h1>

{% for dog in dogs %}
    <div class="card">
        <a href="{% url 'detail' dog.id %}">
            <div class="card-content">
            <span class="card-title">{{ dog.name }}</span>
            <p>Breed: {{ dog.breed }}</p>
            <p>Description: {{ dog.description }}</p>
            {% if dog.age > 0 %}
            <p>Age: {{ dog.age }}</p>
            {% else %}
                <p>Age: Puppy</p>
            {% endif %}
        </div>
    </a>
    </div>
{% endfor %}
{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home</h1>

{% endblock %}

main_app/templates/main_app/dog_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Delete Dog</h1>

<h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' object.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/dog_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
  <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
  <h1>Add Dog</h1>
{% endif %}

  
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn" />
</form>
{% endblock %}

main_app/templates/main_app/treat_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Delete Treat</h1>

<h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'treats_detail' object.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/treat_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Treat Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ treat.name }}</span>
        <p>Brand: {{ treat.brand }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'treats_update' treat.id %}">Edit</a>
        <a href="{% url 'treats_delete' treat.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/treat_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Treat </h1>
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="post">
	<!-- Django requires the following for security purposes -->
	{% csrf_token %}
	<table>
		<!-- Render the inputs inside of <tr>s & <td>s -->
		{{ form.as_table }}
	</table>
	<input type="submit" value="Submit!" class="btn">
</form>
{% endblock %}

main_app/templates/main_app/treat_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Treat List</h1>

{% for treat in treat_list %}
    <a href="{% url 'treats_detail' treat.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ treat.name }}</span>
            <p>Color: {{ treat.brand }}</p>
        </div>
    </div>
    </a>
{% endfor %}

{% endblock %}